### ISSUE TITLE
icm20649 imu support

### ISSUE THREAD

**Issue by mvschaefer** [RCmags/imuFilter#7]
i have installed the imuFilter library and have ported it to:
- esp32
- icm20649 6dof imu

I'm interested in learning more about the quaternion, but i can't find any relevant source code that defines the fields of the quat_t type.
- where can i find the definition of quat_t?

thanks for the repository!

**Comment by RCmags** [comment]
Hi! Thanks for the kind comment. 

The quaternion type of part of the [vector_datatype](https://github.com/RCmags/vector_datatype) class. In there you will find all its relevant fields in the [quaternion_type.cpp](https://github.com/RCmags/vector_datatype/blob/main/src/quaternion_type.cpp) file.
